// tailwind.config.js
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "btn",
    "fab",
    "btn-primary",
    "btn-secondary",
    "btn-accent",
    "btn-info",
    "btn-success",
    "btn-warning",
    "btn-error",
    "btn-outline",
    "btn-dash",
    "countdown",
    "breadcrumbs",
    "btn-soft",
    "link",
    "btn-ghost",
    "btn-link",
    "btn-active",
    "btn-disabled",
    "btn-xs",
    "btn-sm",
    "btn-md",
    "btn-lg",
    "btn-xl",
    "btn-wide",
    "btn-block",
    "btn-square",
    "btn-circle",
  ],
  plugins: [require("daisyui")],
};
